### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by wolet** [uaca/deepy#13]
When I run baseline_rnnlm.py in experiments/ I get "TypeError: 'NoneType' object is not callable".

File "/deepy/experiments/lm/deepy/utils/fake_generator.py", line 12, in __iter__
    return getattr(self.dataset, self.method_name)()
TypeError: 'NoneType' object is not callable

**Comment by zomux** [comment]
Hi,

Sorry for the inconvenience, commit b69bc618ea80cc27dd47bd63c4a3391fcd3e8b7b fixed this.

I should really consider to use some CI tools to monitor those experiment codes.

**Comment by wolet** [comment]
now it works!
