### ISSUE TITLE
Using `theano` on Windows platform does not increase speed

### ISSUE THREAD

**Issue by vit1251** [uaca/deepy#16]
I have follow output

```bash
WARNING (theano.configdefaults): g++ not detected ! Theano will be unable to execute optimized C-implementations (for both CPU and GPU) and will default to Python implementations. Performance will be severely degraded. To remove this warning, set Theano flags cxx to an empty string.
```

But have Microsoft Python compiler pack, Visual Studio 12.0, Visual Studio 11.0, ...

**Comment by zomux** [comment]
You need to install the compiler or only the python code will be executed.

**Comment by vit1251** [comment]
@zomux I have three or more Visual Studio and Microsoft Python Compiler pack ... This is problem setuptools or you setup script?

**Comment by zomux** [comment]
@vit1251 Anyway, if you want to use GPU, linux environment is almost necessary.

**Comment by vit1251** [comment]
Okay.
