### ISSUE TITLE
Regarding developing tutorial to use deepy 

### ISSUE THREAD

**Issue by urwithajit9** [uaca/deepy#4]
Hi Admin,

Do you have any plan to create a documentation or tutorial on How to use deepy? 

I would like to contribute.

Please let me know.

Thanking You.

**Comment by zomux** [comment]
Hi,

Glad to hear there is a volunteer for contribution.

The purpose for deepy is somehow different from other frameworks such as **keras** and **theanets**, which plans to provide DNNs as blackboxes with simple interface.

The purpose of deepy is mainly for research. Build models in a short time and test it out, without worrying about exploding gradients. Anyway, a clean high-level interface is still crucial.

Anyway, I plan to create a tutorial on how to build customized models and conduct experiments with deepy.

Other than that, the current plan for development is to build following models:
- Language models
- Neural machine translation
- Models related with Neural turing machine
 - For example, DRAW
- Models with reinforcement learning
 - Deep Q learning is already done
- Word 2 Vec if I have time

So, actually there are many works to do.

**Comment by zomux** [comment]
Okay, I will create a brief tutorial these days.

**Comment by urwithajit9** [comment]
Hi,

Happy to see the to-do list.

I am new to Machine learning so if you can assign task basis job i will be able to complete in given time.

With Regards.
Ajit

**Comment by ganarajpr** [comment]
:+1:
