### ISSUE TITLE
Pip version error

### ISSUE THREAD

**Issue by ddofer** [uaca/deepy#6]
Installing via pip (latest version - 1 day old) results in an error:

C:\Users\dd>pip install deepy
Collecting deepy
  Downloading deepy-0.1.4.tar.gz (94kB)
    100% |################################| 98kB 330kB/s
    Complete output from command python setup.py egg_info:
    Using gpu device 0: GeForce GTX 970M
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\ddofer\appdata\local\temp\pip-build-vtis_g\deepy\setup.py", line 12, in <module>
        requirements = open(os.path.join(os.path.dirname(__file__), 'requirements.txt')).read().strip().split("\n")
    IOError: [Errno 2] No such file or directory: 'c:\\users\\dd\\appdata\\local\\temp\\pip-build-vtis_g\\deepy\\req
uirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\ddofer\appdata\local\temp\pip-build-vtis_g\deepy

**Comment by zomux** [comment]
Fixed in commit 3e5fbd450e42e38c81aa3a879229c1ccccbf6df2
