### ISSUE TITLE
DRAW / attention zoomer

### ISSUE THREAD

**Issue by jbornschein** [uaca/deepy#7]
Hi,

cool library with an impressive variety of models -- I will take a closer look!

I noticed some code in your DRAW model was cut-n-pasted from jbornschein/draw. I don't mind and rather feel honored; but do you mind attributing it correctly? 

The license on that code is also technically GPL V3 -- I wanted to ensure that enhancements stay open source. But it's OK with me if those parts here are now under the MIT license.

**Comment by zomux** [comment]
Hi,

As I did not do any kind of promotion, I don't know why so many people noticed this project in a sudden.

For the implementation of DRAW, most of the core components are copied from jbornschein/draw.

I'm sorry for that I did not notice the license of your code is GPL, and according to it's description, any derived projects must be published in the same license, so I have moved the implementation to a separated project: https://github.com/uaca/deepy-draw .

Sorry for the inconvenience for this.

**Comment by jbornschein** [comment]
There was a link to deepy on reddit -- I guess thats where a lot of people found it (me included). And thanks for your quick reply! I actually like the description you added a lot and might add something like that to my repository too.
