### ISSUE TITLE
ImportError: cannot import name NeuralLayer

### ISSUE THREAD

**Issue by andyyuan78** [uaca/deepy#8]
ubgpu@ubgpu:~/github/deepy$ sudo python experiments/attention_models/baseline.py
[sudo] password for ubgpu: 
Using gpu device 0: GeForce GTX 970
Traceback (most recent call last):
  File "experiments/attention_models/baseline.py", line 8, in <module>
    from baseline_model import get_network
  File "/home/ubgpu/github/deepy/experiments/attention_models/baseline_model.py", line 14, in <module>
    from deepy.networks import NeuralLayer
ImportError: cannot import name NeuralLayer
ubgpu@ubgpu:~/github/deepy$

**Comment by zomux** [comment]
Sorry, Attention models are not working now, because the framework of deepy greatly changed in the version 0.0.8, I will try to repair it these days.

**Comment by robotzheng** [comment]
thanks.
