### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by wolet** [uaca/deepy#9]
For all examples I get this error. I tried to increase [recursion depth](http://stackoverflow.com/questions/8177073/python-maximum-recursion-depth-exceeded) did not work.

**Comment by zomux** [comment]
Make sure you are using Python 2.7

**Comment by ollehudga** [comment]
Fixed it. I have sent a pull request with the required fix for this

**Comment by wolet** [comment]
I use Python 2.7.9.

**Comment by zomux** [comment]
Hi,

This issue is fixed in commit 493b855f55b18562fe991666eafec37d3116a27c

**Comment by zomux** [comment]
Please run 

```
git pull
```

**Comment by wolet** [comment]
that commit fixed thanks!
